### ISSUE TITLE
Add STARCounts data for TARGET cohorts

### ISSUE THREAD

**Issue by ayan-b** [ucscXena/xena-GDC-ETL#56]

**Comment by yunhailuo** [comment]
Thanks. A great start! Let's do it this way. @maryjgoldman

**Comment by maryjgoldman** [comment]
Should be just the TARGET cohorts. No TCGA cohorts have this data I think

**Comment by maryjgoldman** [comment]
Ayan [10:57 AM]
The columns are `#gene    unstranded    stranded_first    stranded_second`.
@mary by second column you mean `unstranded`? (edited) 


yunhai_luo [11:05 AM]
Yes, second column is unstranded which we want. It's corresponding to HTSeq results.

**Comment by ayan-b** [comment]
There are 4 rows on top of each file something like:

```
N_unmapped    1464118    1464118    1464118
N_multimapping    9269228    9269228    9269228
N_noFeature    39685667    82550515    40374105
N_ambiguous    5442948    55628    3634217
```

Not adding those in the xena matrix.

**Comment by yunhailuo** [comment]
There is really just "TARGET-ALL-P3" for now.

**Comment by yunhailuo** [comment]
> There are 4 rows on top of each file something like:
> 
> ```
> N_unmapped    1464118    1464118    1464118
> N_multimapping    9269228    9269228    9269228
> N_noFeature    39685667    82550515    40374105
> N_ambiguous    5442948    55628    3634217
> ```
> 
> Not adding those in the xena matrix.

We will keep them there for now and worry about removing later if needed, @ayan-b .

**Comment by maryjgoldman** [comment]
Spot check of this data looks good. Very good concordance between HTseq Counts and this data. Almost looks identical in the browser but if you download you can see it is not. 

Going to run it by Jing now

**Comment by maryjgoldman** [comment]
Jing took a look and approved. This is ready to be released along with the rest of the data.

I'm going to close this.
