### ISSUE TITLE
Add CPTAC cohort

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-GDC-ETL#57]
Should be just RNAseq data and clinical data from the API (no xml files)

**Comment by maryjgoldman** [comment]
take all all all API fields that have data, don't filter by TCGA standards
If hit fields with multiple values, highlight these fields for Mary to review
and leave out as a first pass

**Comment by ayan-b** [comment]
Added RNASeq data.

**Comment by maryjgoldman** [comment]
Clinical API endpoints to keep: https://docs.google.com/spreadsheets/d/11JcG3j0-RzT3PgyQz2XiEKeTqBSs_nnAdOwYnZRmTDk

**Comment by ayan-b** [comment]
Noticed that some `cases.samples.submitter_id` is empty. So should I remove those or set something else (`cases.case_id`) as an index?

**Comment by ayan-b** [comment]
Added phenotype matrix generation in https://github.com/ucscXena/xena-GDC-ETL/pull/34.

**Comment by maryjgoldman** [comment]
I'll check out the `cases.samples.submitter_id` to see if we should keep. It's not a particularly important field as far as clinical data goes. More for folks looking for batch effects among the submitters.

**Comment by yunhailuo** [comment]
`cases.samples.submitter_id` is the sample ID we use for all matrices in TCGA. To my understanding, that's *the most important* info. What is the sample ID for CPTAC? I couldn't found any sample data on hub.

**Comment by maryjgoldman** [comment]
> `cases.samples.submitter_id` is the sample ID we use for all matrices in TCGA. To my understanding, that's _the most important_ info. What is the sample ID for CPTAC? I couldn't found any sample data on hub.

Oh, I see! That's what you were saying @ayan-b - it is the index. Sorry for not understanding

@ayan-b can you provide a tsv file with `cases.samples.submitter_id` and `cases.case_id` for all samples in the CPTAC cohort? We'll need to look into this more closely. Also, is there a UUID associated with the samples too?

**Comment by ayan-b** [comment]
Uploaded.

**Comment by maryjgoldman** [comment]
Also, as a note I'm seeing 322 cases on the GDC portal:
![Screen Shot 2019-07-03 at 10 52 58 AM](https://user-images.githubusercontent.com/13877333/60613967-c2bc3600-9d80-11e9-81f5-05f2af1e1844.png)

And 469 on ours:
![Screen Shot 2019-07-03 at 10 49 16 AM](https://user-images.githubusercontent.com/13877333/60613947-bc2dbe80-9d80-11e9-846d-e0a162e296e2.png)

**Comment by yunhailuo** [comment]
This should be  the link for all cases in CPTAC: https://api.gdc.cancer.gov/cases/?fields=samples.submitter_id,samples.sample_id&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.program.name%22%2C%22value%22%3A%5B%22CPTAC%22%5D%7D%7D%5D%7D&size=333&pretty=true

Every sample in it has both submitter_id and sample_id.

**Comment by yunhailuo** [comment]
> **Also, as a note I'm seeing 322 cases on the GDC portal:**
> ![Screen Shot 2019-07-03 at 10 52 58 AM](https://user-images.githubusercontent.com/13877333/60613967-c2bc3600-9d80-11e9-81f5-05f2af1e1844.png)
> 
> **And 469 on ours:**
> ![Screen Shot 2019-07-03 at 10 49 16 AM](https://user-images.githubusercontent.com/13877333/60613947-bc2dbe80-9d80-11e9-846d-e0a162e296e2.png)

Against TCGA-GBM?

**Comment by maryjgoldman** [comment]
Sorry, wrong screenshot. I edited my comment with the correct screenshot. I am also attaching it here

![Screen Shot 2019-07-03 at 10 52 47 AM](https://user-images.githubusercontent.com/13877333/60615384-d74dfd80-9d83-11e9-9203-9aae5f4a2353.png)

**Comment by yunhailuo** [comment]
> Sorry, wrong screenshot. I edited my comment with the correct screenshot. I am also attaching it here
> 
> ![Screen Shot 2019-07-03 at 10 52 47 AM](https://user-images.githubusercontent.com/13877333/60615384-d74dfd80-9d83-11e9-9203-9aae5f4a2353.png)

Isn't that number of samples meaning 469 samples from 322 cases? Similar case for TCGA-BRCA where we have n=1,217 for HTSeq - Counts corresponding to 1092 cases on GDC.

**Comment by maryjgoldman** [comment]
True. My comment was not helpful information for debugging why the `cases.samples.submitter_id` is blank for so many cases. 

I have been googling around to try to figure out why `cases.samples.submitter_id` is blank for so many cases. I will report when I know more though I'm not seeing much information about this. It is likely we will need to ask the GDC. I do not want to use another column, like `cases.demographic.submitter_id` or `cases.case_id`, until we understand why this is happening.

**Comment by yunhailuo** [comment]
> why cases.samples.submitter_id is blank for so many cases

Are you talking about missing `cases.samples.submitter_id` in the sample TSV? I didn't check all. But some of them might be because the row (which is file instead of sample) is associated with more than one sample:

* https://api.gdc.cancer.gov/files/37832802-e1f4-43f7-bc46-67bcc4233f2b?fields=cases.samples.sample_id
    vs
* https://api.gdc.cancer.gov/files/9e38d9d5-190e-4ba9-a4f1-e2d66f600b46?fields=cases.samples.sample_id

We need to look into both the code and the data. I need some time later to check that. A quick get from me is:
1. Each row in phenotype data should be a sample not a file (the id column BS at the end is file ID; that's why I say/guess that sample TSV matrix is file per row). This is a mistake in our code. I'll check later.
2. It's strange a single aliquot belongs to two samples:
* CPT0147980010 belongs to both C3N-02586-01 and C3N-02586-02: https://portal.gdc.cancer.gov/cases/8919013d-01db-4469-b0a6-553dd25fda6d?bioId=73ee6f62-37dc-43b0-8ff4-0a8c1c1a2f17.
Maybe there is a reason behind it. We need to look around first. If we can't understand, we should ask GDC.

**Comment by yunhailuo** [comment]
Just a note here, PR #34 has been repurposed to import phenotype data for CPTAC projects for this issue.
