### ISSUE TITLE
Remove blood normals from new segmented copy number datasets

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-GDC-ETL#60]
The new segmented copy number datasets (DNAcopy) have copy number data for samples that are blood normal. We only want copy number data for the tumor samples. 

![Screen Shot 2019-07-01 at 4 16 42 PM](https://user-images.githubusercontent.com/13877333/60471985-e0bc5600-9c1b-11e9-97f6-788ead167032.png)

The samples in black are the samples for which we want to remove the segmented copy number data for.

[newCNV-bloodnormaltoberemoved.txt](https://github.com/yunhailuo/xena-GDC-ETL/files/3347628/newCNV-bloodnormaltoberemoved.txt)

This is a bookmark of the above data. It can be imported back into Xena via the bookmark menu

**Comment by maryjgoldman** [comment]
The Masked segmented copy number dataset already removes these samples. Please follow the code that was already written for this

**Comment by yunhailuo** [comment]
CNV and Mased CNV are treated similarly.

Remove blood normal was done for clinical data: https://github.com/yunhailuo/xena-GDC-ETL/blob/master/xena_gdc_etl/xena_dataset.py#L1622-L1631

**Comment by maryjgoldman** [comment]
One of the samples in the screenshot and bookmark I provided that has no clinical data but has segmented cnv data is TCGA-19-0955-10A. If you look this up in the GDC, you see it is a blood derived.

https://portal.gdc.cancer.gov/cases/f473a0d0-72b6-465e-93f7-122224960e80?bioId=92c6077b-35ab-403a-9f26-374b0702717d

![Screen Shot 2019-07-01 at 4 42 24 PM](https://user-images.githubusercontent.com/13877333/60472818-38a88c00-9c1f-11e9-8208-fd055329a94b.png)

**Comment by maryjgoldman** [comment]
If there is no code already written for removing blood derived normal from the masked segmented copy number we need to write it for the segmented cnv

**Comment by yunhailuo** [comment]
These are all TCGA data on blood derived normal samples: https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.program.name%22%2C%22value%22%3A%5B%22TCGA%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.samples.sample_type%22%2C%22value%22%3A%5B%22Blood%20Derived%20Normal%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.access%22%2C%22value%22%3A%5B%22open%22%5D%7D%7D%5D%7D&searchTableTab=files

You should see some of them in CNV, Masked CNV and 4 types of SNV data. Have you?

**Comment by yunhailuo** [comment]
I'm really sorry. My bad. Masked CNV data are filtered for blood derived normal here: https://github.com/yunhailuo/xena-GDC-ETL/blob/master/xena_gdc_etl/xena_dataset.py#L874-L893

I might be getting really close to Alzheimer or something...

**Comment by yunhailuo** [comment]
@ayan-b Please add that filter to CNV data (4 lines above). Thank you!

**Comment by ayan-b** [comment]
Added CNV data to the hub.

**Comment by maryjgoldman** [comment]
This looks good. Blood derived normals are removed
