### ISSUE TITLE
Add min:-1 max:1 to GISTIC .json files 

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-GDC-ETL#61]
Add min:-1 max:1 to the .json files that go with the GISTIC files. This will help the data display better.

This will look similar to how the DNA methylation data has min:0 max:1

**Comment by maryjgoldman** [comment]
This looks good for the CHOL dataset on the hub. Please update this for all other GISTIC datasets in all other cohorts.

**Comment by ayan-b** [comment]
Added for all cohorts.

**Comment by maryjgoldman** [comment]
QA for amplified genes looks good. Attaching results from my tests. Still need to test deleted genes.

Example 1:
![Screen Shot 2019-07-02 at 2 51 45 PM](https://user-images.githubusercontent.com/13877333/60549214-12dfbd80-9cd9-11e9-9ed9-6fcc301317d7.png)
[GBM_CDKN2A_CDKN2B.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3352447/GBM_CDKN2A_CDKN2B.txt)

Example 2:
![Screen Shot 2019-07-02 at 2 55 23 PM](https://user-images.githubusercontent.com/13877333/60549376-8b467e80-9cd9-11e9-8656-38521fb3a3b3.png)
[BRCA_ERBB2_Her2_immuno_score.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3352456/BRCA_ERBB2_Her2_immuno_score.txt)

**Comment by maryjgoldman** [comment]
Looking at genes that are typically deleted, I do not see a close correspondence between the segmented CNV and the GISTIC data. While this is worrisome, I see the same trend in the legacy TCGA data between the GISTIC data generated by Firehose and the segmented data generated by TCGA. So perhaps this is a well known trend.

Looked at genes in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2921682/

New GDC data:
![Screen Shot 2019-07-03 at 9 28 21 AM](https://user-images.githubusercontent.com/13877333/60608902-5ab42280-9d75-11e9-88bd-e60e16f0a551.png)
Bookmark: [GDC_LUAD_FHIT.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3355919/GDC_LUAD_FHIT.txt)

Legacy TCGA:
![Screen Shot 2019-07-03 at 9 29 13 AM](https://user-images.githubusercontent.com/13877333/60608943-6ef81f80-9d75-11e9-99b2-8977104d73f4.png)
Bookmark: [Legacy_LUAD_FHIT.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3355920/Legacy_LUAD_FHIT.txt)

**Comment by maryjgoldman** [comment]
Just so it's here, I'm putting one of the most egregious non-correspondence between the GISTIC and cnv data here. Note that it is not seen for the legacy TCGA data.

PTEN for GBM
![Screen Shot 2019-07-03 at 10 48 15 AM](https://user-images.githubusercontent.com/13877333/60613721-517c8300-9d80-11e9-8622-2f8af9cc5a95.png)
Bookmark: [New_GDC_PTEN_GBM.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3356238/New_GDC_PTEN_GBM.txt)

PTEN for legacy TCGA data
![Screen Shot 2019-07-03 at 10 49 16 AM](https://user-images.githubusercontent.com/13877333/60613745-5e00db80-9d80-11e9-9920-84305ae7f00c.png)
Bookmark: [legacy_TCGA_PTEN_GBM.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3356243/legacy_TCGA_PTEN_GBM.txt)

**Comment by maryjgoldman** [comment]
Email out to the GDC about this ...
