### ISSUE TITLE
Generate and load TARGET phenotype data

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-GDC-ETL#69]
Model this data after the other TARGET phenotype datasets.

**Comment by maryjgoldman** [comment]
Just changed this to all TARGET phenotype data. All TARGET cohorts are missing phenotype data

**Comment by ayan-b** [comment]
@maryjgoldman Loaded data into the hub.

**Comment by yunhailuo** [comment]
PR #70 is related to TARGET phenotype data but it's quite off and current parsing some files which are irrelevant. Feel free to check the data and just keep that in mind, @maryjgoldman

**Comment by yunhailuo** [comment]
Don't really know the status of this issue. I'll personally consider it as in progress together with #70 and not worry about it.

Overall, what happened is TARGET program has multiple XLSX files for clinical data for each project and there is not way to tell which one is the right one from metadata. So I gauge them based on a sheet named "Clinical Data" in the file. The reader function will try to read that sheet. If it fails, it knows the file is not relevant and will simply skip it with a message.

My understanding, based on discussions here and there, is we all agreed on that criteria?

**Comment by maryjgoldman** [comment]
@ayan-b Starting to QA this. I can see that the data loaded is similar to what we loaded in the past. Is this data from the API or XML or both?

**Comment by maryjgoldman** [comment]
@ayan-b Also, GDC TARGET-CCSK has a phenotype file but no samples in it

**Comment by ayan-b** [comment]
> @ayan-b Starting to QA this. I can see that the data loaded is similar to what we loaded in the past. Is this data from the API or XML or both?

Both.

> @ayan-b Also, GDC TARGET-CCSK has a phenotype file but no samples in it

There is a separate script for `TARGET-CCSK` phenotype, running that now.

**Comment by maryjgoldman** [comment]
For CCSK there are a lot more identifiers compared to the other TARGET cohorts and more identifiers than what is in the old GDC hub. Why is this?

**Comment by ayan-b** [comment]
Because more data is available from the API now ...

**Comment by maryjgoldman** [comment]
This looks great from the data side
