### ISSUE TITLE
Add CTSP-DLBCL Cohort

### ISSUE THREAD

**Issue by ayan-b** [ucscXena/xena-GDC-ETL#72]

**Comment by maryjgoldman** [comment]
Please hold off

**Comment by maryjgoldman** [comment]
Seems fairly simple in structure. Tumor only. RNAseq only. FPKM, FPKM-UQ, HTseq counts. Right now 45 cases

https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/clinical-trial-sequencing
Clinical Trial Sequencing Project (CTSP). CTSP’s goal is to elucidate the molecular basis of response and resistance to therapies studied. The cancer types currently under study are breast cancer, renal cell carcinoma, and diffuse large B-cell lymphoma.

Treated 430 DLBCL patients with rituximab, an antibody that targets B cells for destruction, in combination with one of two different chemotherapy regimens. By randomly assigning patients to either R-CHOP or Dose Adjusted-EPOCH-R, the study aims to establish which chemotherapy best complements rituximab in the treatment of DLBCL and to develop a molecular predictor of patient responses.
