### ISSUE TITLE
Add explanatory metadata to GISTIC cohorts

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-GDC-ETL#74]
We heard back from the GDC re:discrepancies between GISTIC and cnv datasets.

They essentially said that the GISTIC -1,0, 1 comes from focal copy number estimates, not actual copy number estimate. Focal means small region (probably some cutoff), large chromosomal level deletion like PTEN does not assigned to focal.

We need to add this to the notes on the datapages for these datasets so we can point people to them if they ask questions.

**Comment by maryjgoldman** [comment]
@ayan-b What text did you add to the metadata for this? I'm realizing I didn't write out exactly what it should say.

**Comment by ayan-b** [comment]
I added this:
```
The GISTIC -1,0, 1 comes from focal copy number estimates, not actual copy number estimate. Focal means small region (probably some cutoff), large chromosomal level deletion like PTEN does not assigned to focal.
```

**Comment by maryjgoldman** [comment]
I see. Can you instead put:

The GDC GISTIC copy number dataset is derived from focal copy number estimates. Larger chromosomal-level deletions may not be not captured in this dataset.

**Comment by ayan-b** [comment]
Updated.
