### ISSUE TITLE
Phenotype data missing for TCGA-14-1401-01A

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/xena-GDC-ETL#79]
In the current GDC data, we have phenotype data for this sample in TCGA GBM:
http://dev.xenabrowser.net/?bookmark=fc019302a920715dd34d4256b78d677e

However, it does not have phenotype data in the most recent release in the hub

**Comment by yunhailuo** [comment]
"TCGA-14-1401-01A" is in the new hub Ayan put together in TCGA-GBM.GDC_phenotype.tsv.gz. Is that not right?

**Comment by maryjgoldman** [comment]
More evidence:

New GDC hub where I am searching for 'TCGA-14-1401-01A' (see filter bar). See that there is *no* sample_type.
![Screen Shot 2019-07-09 at 8 46 09 AM](https://user-images.githubusercontent.com/13877333/60903570-73658200-a226-11e9-8003-aa6d0bc234f9.png)
Bookmark: 
[NewGDChub.txt](https://github.com/ucscXena/xena-GDC-ETL/files/3373817/NewGDChub.txt)


Old GDC hub where I am searching for 'TCGA-14-1401-01A' (see filter bar). See that there *is* sample_type.
![Screen Shot 2019-07-09 at 8 48 51 AM](https://user-images.githubusercontent.com/13877333/60903555-6d6fa100-a226-11e9-85f3-09e004f93692.png)
Bookmark: http://dev.xenabrowser.net/?bookmark=08002712ff993690a146044d9ceb99fc

**Comment by maryjgoldman** [comment]
In the most recent data on the new hub, this data is there. Going to close this though will keep an eye out for this in the future
