### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by ayan-b** [ucscXena/xena-GDC-ETL#9]
The project can be released to pypi so that it can be easily downloaded by pip or other installers.

**Comment by yunhailuo** [comment]
That's a good suggestion. Since this is for Xena, I'd like to check with @maryjgoldman or @jingchunzhu to see if this is what we want to have.

**Comment by ayan-b** [comment]
@yunhailuo also we need to add a LICENSE file. Which LICENSE does ucscxena follow?

**Comment by yunhailuo** [comment]
This is a very legitimate suggestion. Again, @maryjgoldman or @jingchunzhu for proper license.

**Comment by ayan-b** [comment]
@yunhailuo ,I think Apache 2.0 as per this site: http://xena.ucsc.edu/ .

**Comment by maryjgoldman** [comment]
Yes, we use the Apache 2.0 license

**Comment by pnijhara** [comment]
@ayan-b Are you still working on this issue? If not , I would like to work on this issue.

**Comment by ayan-b** [comment]
Ideally maintainers should release to pypi.

**Comment by pnijhara** [comment]
No issues.

**Comment by yunhailuo** [comment]
> > @ayan-b Are you still working on this issue? If not, I would like to work on this issue.
> 
> Ideally maintainers should release to pypi.

I have no problem releasing it. As mentioned in my first comment, I'd like to have confirmation from @maryjgoldman or @jingchunzhu.

**Comment by maryjgoldman** [comment]
Just realizing I never got back to you guys on this. I checked with Jing and she said this is fine to do.

**Comment by yunhailuo** [comment]
> Just realizing I never got back to you guys on this. I checked with Jing and she said this is fine to do.

Thanks for checking. I'll do a test release and we can take a look first, @maryjgoldman and @ayan-b

**Comment by yunhailuo** [comment]
Test release to be reviewed: https://test.pypi.org/project/xena-gdc-etl/

**Comment by maryjgoldman** [comment]
I don't know enough about python to know if this works but the links above works and has a lot of great documentation. As we don't expect many people to interact with the code in this way, I vote we approve this and then if people complain then we can go back and change this.

**Comment by yunhailuo** [comment]
One potential plan could be releasing this version at the end of GSoC as one end product, @maryjgoldman ?

**Comment by maryjgoldman** [comment]
How does this work? Like if we change the code, will the pypi package update as well? Or is more like we release our code to pypi?

**Comment by yunhailuo** [comment]
No automatic update. Up to what we release (push). Usually a collection of mature codes for a release.

**Comment by maryjgoldman** [comment]
Gotcha. Then I defer to you, @yunhailuo, when we should release this. Should we put this back in the 'to do' queue until we're ready to release at the end of the project?

**Comment by yunhailuo** [comment]
Thanks. Leave it there because the releasing command is ready. I will check the code and release when we get close to the end of the program.
